timestamp_20100101_000000_utc = 1262304000

EGTS_MIN_TRANSPORT_LENGTH = 11
EGTS_PROTOCOL_VERSION = 1
EGTS_PT_RESPONSE = 0
EGTS_PT_APPDATA = 1
PREFIX_NUMBER = 0
EGTS_SERVICE_LAYER_MIN_RECORD_HEADER_LEN = 7

# SERVICE LAYER
EGTS_AUTH_SERVICE = 1
EGTS_TELEDATA_SERVICE = 2

# SERVICE EGTS_AUTH_SERVICE SUBRECORD

EGTS_SR_RECORD_RESPONSE = 0
EGTS_SR_TERM_IDENTITY = 1

# SERVICE EGTS_TELEDATA_SERVICE SUBRECORD

EGTS_SR_POS_DATA = 16
